### ISSUE TITLE
Observer overrides core observer

### ISSUE THREAD

**Issue by hrmjohnson** [etailer/Etailer_CouponUsed#2]
Hello, thanks for this module. 

I did notice an error that causes coupons that have a discount value > $0 to not be marked as used. The reason for this is your observer in config.xml is named exactly the same as the core SalesRule observer is. This results in your module _overriding_ the core functionality as opposed to working as an addendum to it. 

I managed to solved this simply by changing the name of the observer in your config file.

**Comment by rjocoleman** [comment]
hello! thanks for this report, would you mind creating a PR to rename the relevant observer please?

**Comment by hrmjohnson** [comment]
Done...I think. Relatively new to using github collaboratively so let me know if I did something wrong!

**Comment by rjocoleman** [comment]
awesome, thanks so much!
